remote_theme: jekyll/minima@1e8a445
minima:
  skin: dark
plugins:
- jekyll-remote-theme
- jekyll-redirect-from
- jekyll-feed
author: Martin Lugton
title: Martin Lugton
description: Tech for good and digital government
show_downloads: false