remote_theme: jekyll/minima@1e8a445
minima:
  skin: auto
plugins:
- jekyll-remote-theme
- jekyll-redirect-from
- jekyll-feed
- jekyll-paginate
author: Martin Lugton
title: Martin Lugton
description: Tech for good and digital government
show_downloads: false
feed:
  post_limit: 50
paginate: 5
paginate_path: "/page:num/"